repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E402"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--strict"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest -q
        pass_filenames: false 